[program:bocao-delivery-queue]
directory=/var/www/html/bocao-bot/laravel
command=/usr/bin/php artisan queue:work database-delivery --queue=telegram-delivery --sleep=1 --tries=3 --timeout=1200
user=www-data
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=1205
stopsignal=TERM
stdout_logfile=/var/www/html/bocao-bot/laravel/storage/logs/delivery-queue-supervisor.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
redirect_stderr=true
environment=APP_ENV="production"
