[program:bocao-queue]
directory=/var/www/html/bocao-bot/laravel
command=/usr/bin/php artisan queue:work --sleep=3 --tries=1 --timeout=14400
user=www-data
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=14405
stopsignal=TERM
stdout_logfile=/var/www/html/bocao-bot/laravel/storage/logs/queue-supervisor.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
redirect_stderr=true
environment=APP_ENV="production"
